[project]
name = "variant-prioritization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.3.3",
    "pysam>=0.23.3",
    "requests>=2.32.5",
    "streamlit>=1.54.0",
    "watchdog>=6.0.0",
]
